import { navigate } from "./router.js";
import { loadMembers, getMemberByCode, saveMember } from "./members.js";
import { escapeHtml } from "./utils.js";
const app=document.querySelector("#app");
export function renderAddMemberPage(){ renderEditor(null,true); }
export async function renderEditMemberPage(code){ const m=getMemberByCode(await loadMembers(),code); if(!m)return navigate("/members"); renderEditor(m,false); }
export async function renderPackagePage(code){ const m=getMemberByCode(await loadMembers(),code); if(!m)return navigate("/members"); renderPackage(m); }
function guard(){ if(sessionStorage.getItem("clob_trainer")!=="true"){navigate("/trainer-login");return false;} return true; }
function renderEditor(m,isNew){ if(!guard())return; const x=m||{}; app.innerHTML=`<main class="page trainer-page"><div class="member-form-screen"><header class="member-form-header"><button id="back" class="back-button">←</button><div><p class="section-label">${isNew?"NEW MEMBER":"MEMBER"}</p><h1>${isNew?"เพิ่มสมาชิก":"แก้ไขสมาชิก"}</h1></div></header><form id="form" class="member-editor card"><div class="form-grid"><label><span>ชื่อ *</span><input name="name" required value="${escapeHtml(x.name||"")}"></label><label><span>รหัส 5 หลัก *</span><input name="code" inputmode="numeric" maxlength="5" required ${isNew?"":"readonly"} value="${escapeHtml(x.code||"")}"></label><label><span>เบอร์โทร</span><input name="phone" value="${escapeHtml(x.phone||"")}"></label><label><span>สถานะ</span><select name="status"><option value="active" ${x.status!=="inactive"?"selected":""}>Active</option><option value="inactive" ${x.status==="inactive"?"selected":""}>Inactive</option></select></label><label><span>เพศ</span><input name="gender" value="${escapeHtml(x.gender==="-"?"":x.gender||"")}"></label><label><span>อายุ</span><input name="age" type="number" value="${x.age==="-"?"":escapeHtml(x.age||"")}"></label><label><span>ส่วนสูง cm</span><input name="height" type="number" step="0.1" value="${x.height==="-"?"":escapeHtml(x.height||"")}"></label><label><span>น้ำหนัก kg</span><input name="weight" type="number" step="0.1" value="${x.weight==="-"?"":escapeHtml(x.weight||"")}"></label><label><span>วันที่สมัคร</span><input name="joinedAt" type="date" value="${escapeHtml(x.joinedAt==="-"?"":x.joinedAt||new Date().toISOString().slice(0,10))}"></label></div><label class="form-wide"><span>เป้าหมาย</span><textarea name="goal" rows="3">${escapeHtml(x.goal==="-"?"":x.goal||"")}</textarea></label><button class="button button-primary">${isNew?"เพิ่มสมาชิก":"บันทึกข้อมูล"}</button></form><div id="toast" class="toast" hidden></div></div></main>`;
 document.querySelector("#back").onclick=()=>navigate(isNew?"/members":`/member-detail-${x.code}`); const ci=document.querySelector('[name="code"]'); ci.oninput=()=>ci.value=ci.value.replace(/\D/g,"").slice(0,5);
 document.querySelector("#form").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),b=e.currentTarget.querySelector("button");b.disabled=true;try{const saved=await saveMember({code:d.get("code"),name:String(d.get("name")).trim(),phone:String(d.get("phone")).trim(),status:d.get("status"),gender:String(d.get("gender")).trim(),age:d.get("age"),height:d.get("height"),weight:d.get("weight"),joinedAt:d.get("joinedAt"),goal:String(d.get("goal")).trim(),package:m?{name:m.packageName,startDate:m.packageStartDate,endDate:m.packageEndDate,price:m.packagePrice,renewal:m.packageRenewal,status:m.packageStatus,features:m.packageFeatures}:undefined},{isNew});navigate(`/member-detail-${saved.code}`);}catch(err){show(err.message);b.disabled=false;}};
}
function renderPackage(m){ if(!guard())return; app.innerHTML=`<main class="page trainer-page"><div class="member-form-screen"><header class="member-form-header"><button id="back" class="back-button">←</button><div><p class="section-label">ONLINE COACHING</p><h1>แพ็กเกจรายเดือน</h1></div></header><section class="monthly-package-note card"><strong>${escapeHtml(m.name)}</strong><p>คิดค่าบริการรายเดือน ไม่มีการนับ Session</p></section><form id="form" class="member-editor card"><div class="form-grid"><label><span>ชื่อแพ็กเกจ</span><input name="name" required value="${escapeHtml(m.packageName==="No Package"?"Online Coaching Monthly":m.packageName)}"></label><label><span>ราคา/เดือน</span><input name="price" type="number" min="0" value="${m.packagePrice||0}"></label><label><span>วันที่เริ่ม</span><input name="startDate" type="date" required value="${m.packageStartDate==="-"?"":m.packageStartDate}"></label><label><span>วันต่ออายุ/หมดอายุ</span><input name="endDate" type="date" required value="${m.packageEndDate==="-"?"":m.packageEndDate}"></label><label><span>Renewal</span><select name="renewal"><option value="manual">Manual</option><option value="auto" ${m.packageRenewal==="auto"?"selected":""}>Auto</option></select></label><label><span>สถานะ</span><select name="status"><option value="active">Active</option><option value="paused" ${m.packageStatus==="paused"?"selected":""}>Paused</option><option value="expired" ${m.packageStatus==="expired"?"selected":""}>Expired</option></select></label></div><fieldset class="package-features"><legend>สิทธิ์ที่รวม</legend><label><input type="checkbox" name="program" checked> โปรแกรมฝึก</label><label><input type="checkbox" name="weeklyCheckin" checked> Weekly Check-in</label><label><input type="checkbox" name="habitTracking" checked> Habit Tracking</label><label><input type="checkbox" name="coachReview" checked> Coach Review</label></fieldset><button class="button button-primary">บันทึกแพ็กเกจ</button></form><div id="toast" class="toast" hidden></div></div></main>`;
 document.querySelector("#back").onclick=()=>navigate(`/member-detail-${m.code}`); document.querySelector("#form").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await saveMember({...m,package:{name:d.get("name"),price:d.get("price"),startDate:d.get("startDate"),endDate:d.get("endDate"),renewal:d.get("renewal"),status:d.get("status"),features:{program:d.has("program"),weeklyCheckin:d.has("weeklyCheckin"),habitTracking:d.has("habitTracking"),coachReview:d.has("coachReview")}}});navigate(`/member-detail-${m.code}`);};
}
function show(msg){const t=document.querySelector("#toast");t.textContent=msg;t.hidden=false;setTimeout(()=>t.hidden=true,2200);}
